"""Harvest the component-property vocabulary from real exports. Sprint 07.

The application layer is configured through name/value `ComponentProperty` bags —
1,610 of them in gs-productretail alone. There is no schema for the valid keys: the
authoring guide abbreviates the whole layer to an ellipsis. Measured, it is regular
(7 renderers, 43 property names, two holders), but those figures are a FLOOR — three
renderers appear in only one sample each.

So the emitter refuses an unknown component or property rather than guessing. A wrong
property key imports cleanly and misbehaves at runtime, which is the worst failure mode
available because it survives validation.

    python -m agent.compile.harvest_vocab samples/*.xml > agent/compile/component_vocab.yaml
"""
from __future__ import annotations

import collections
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

HOLDERS = ("TableColumn", "FormField", "FDNFormField")


def harvest(*paths: str | Path) -> dict:
    comps: dict[str, set[str]] = collections.defaultdict(set)
    values: dict[str, set[str]] = collections.defaultdict(set)
    holders: set[str] = set()
    for p in paths:
        root = ET.parse(p).getroot()
        for el in root.iter():
            name = el.find("componentName")
            if name is None:
                continue
            holders.add(el.tag)
            cn = name.text or ""
            for cp in el.iter("ComponentProperty"):
                key = cp.findtext("name")
                if not key:
                    continue
                comps[cn].add(key)
                v = cp.findtext("value")
                if v is not None and len(v) <= 24:
                    values[key].add(v)
    return {
        "sources": [Path(p).name for p in paths],
        "holders": sorted(holders),
        "components": {c: sorted(ps) for c, ps in sorted(comps.items())},
        "observed_values": {k: sorted(v) for k, v in sorted(values.items()) if v},
    }


if __name__ == "__main__":
    import yaml
    print("# GENERATED by agent/compile/harvest_vocab.py — do not hand-edit.")
    print("# A FLOOR, not a ceiling: xDM certainly ships renderers these models never use.")
    print(yaml.dump(harvest(*sys.argv[1:]), sort_keys=False, width=100))
