"""Sprint 11 acceptance: completeness advice.

Every rule gets a mutation test — take a scenario that is clean, remove the thing, and
assert the question appears. A gap rule that cannot be made to fire is decorative, and
one that fires on a good design is noise.
"""
from __future__ import annotations

import copy
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
ROOT = Path(__file__).resolve().parents[1]
from agent.ir.advise import advise  # noqa: E402
from agent.ir.schema import IR, Attribute, Publisher  # noqa: E402
from agent.ir.validate import errors, validate  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "out"


def load(name):
    d = OUT / name
    return IR.load(d / "ir" / "model.yaml", d / "ir" / "certify.yaml")


def rules(ir):
    return {g.rule for g in advise(ir)}


@pytest.fixture
def s2():
    return load("s2-two-crms")


@pytest.fixture
def s4():
    return load("s4-multi-source-ids")


@pytest.fixture
def s3():
    return load("s3-three-sources")


# ------------------------------------------------------------------- quiet on good
def test_the_lov_scenario_raises_nothing():
    """An LOV has no certification process, so no gap rule may misfire on it."""
    assert advise(load("s1-country-reference")) == []


def test_the_id_matched_scenario_is_clean(s2):
    assert advise(s2) == []


def test_the_fuzzy_scenario_is_clean_because_every_gap_is_answered_on_disk(s3):
    """CA-003 was the operator's call, answered and acknowledged in the IR with the
    design recorded in 04-app-plan.md § The steward queue.

    CA-018 joined it later: this model overwrites both address members in place, which
    is real and unrecoverable. It is acknowledged rather than fixed because this is the
    DEPLOYED, RUNNING application — splitting a complex-type member needs a redeploy and
    a migration for records whose raw values are already gone. The acknowledgement
    carries that reasoning in model.yaml, which is the point: a deferral with a known
    cost, on disk, rather than a quiet omission.
    """
    acked = s3.model_ir.acknowledged_gaps
    assert "CA-003:Party" in acked
    assert sum(1 for a in acked if a.startswith("CA-018:")) == 2
    assert advise(s3) == []


# --------------------------------------------------------------- one test per rule
def test_ca001_no_validations(s2):
    s2.certify.validations = []
    assert "CA-001" in rules(s2)


def test_ca002_attribute_with_no_survivorship(s2):
    s2.certify.survivorship = []
    g = next(x for x in advise(s2) if x.rule == "CA-002")
    assert "which value wins" in g.question and "Email" in g.question


def test_ca003_fuzzy_entity_needs_a_steward_queue(s3):
    s3.model_ir.acknowledged_gaps = []          # the rule, not the acknowledgement
    assert "CA-003" in rules(s3)


def test_ca004_match_rules_reading_only_raw_source_values(s3):
    s3.certify.enrichers = []
    assert "CA-004" in rules(s3)


def test_ca005_no_subject_name(s2):
    s2.model_ir.entities[0].subject_name = None
    assert "CA-005" in rules(s2)


def test_ca006_nothing_searchable(s2):
    for a in s2.model_ir.entities[0].attributes:
        a.searchable = False
    assert "CA-006" in rules(s2)


def test_ca007_several_publishers_and_none_preferred(s2):
    for s in s2.certify.survivorship:
        s.strategy = "LARGEST_VALUE"
        s.publisher_rankings = []
    assert "CA-007" in rules(s2)


def test_ca008_only_exact_matches_merge(s3):
    for r in s3.certify.matchers[0].rules:
        r.score = 100
    assert "CA-008" in rules(s3)


def test_ca009_lov_typed_attribute_that_constrains_nothing():
    ir = load("s1-country-reference")
    ir.model_ir.entities.append(
        type(ir.model_ir).model_fields["entities"].annotation.__args__[0](
            name="Shipment", type="basic", subject_name="Destination",
            attributes=[Attribute(name="Destination", type="Country",
                                  lov_scope="NONE", searchable=True)]))
    assert "CA-009" in rules(ir)


def test_ca010_mandatory_that_enforces_nothing(s2):
    s2.model_ir.entities[0].attributes[0].mandatory_scope = "NONE"
    assert "CA-010" in rules(s2)


# ----------------------------------------------------------------- noise controls
def test_a_generated_golden_id_is_not_asked_about(s3):
    """A fuzzy entity's PK is generated by xDM, so a scope on it constrains nothing."""
    pk = next(a for a in s3.model_ir.entities[0].attributes if a.pk)
    assert pk.mandatory and pk.mandatory_scope == "NONE"
    assert "CA-010" not in rules(s3)


def test_derived_attributes_are_not_asked_about_for_survivorship(s3):
    """PRE_CONSO enricher outputs are computed, not supplied by a publisher, so
    'which source wins' is the wrong question for them."""
    derived = {e.attribute for en in s3.certify.enrichers for e in en.expressions}
    assert derived
    assert "CA-002" not in rules(s3)


def test_acknowledging_a_gap_closes_THAT_gap_and_no_other(s3):
    """Acknowledging is per (rule, where). Asserting `advise(s3) == []` after
    acknowledging ONE key used to pass only because s3 happened to have one gap class;
    it then failed the day the model grew a second, which made a test about the
    MECHANISM depend on a snapshot of the scenario."""
    s3.model_ir.acknowledged_gaps = ["CA-003:Party"]
    keys = {g.key for g in advise(s3)}
    assert "CA-003:Party" not in keys
    assert keys, "the other gaps must survive — an acknowledgement is not a mute button"
    assert all(k.startswith("CA-018:") for k in keys)


def test_acknowledging_by_rule_id_closes_every_instance(s3):
    """A bare rule id is the blanket form: it closes every instance of that rule."""
    s3.model_ir.acknowledged_gaps = ["CA-018"]
    keys = {g.key for g in advise(s3)}
    assert not [k for k in keys if k.startswith("CA-018:")], \
        "a bare rule id must close BOTH CA-018 instances, not just one"
    assert "CA-003:Party" in keys, "and must not close a different rule"


# ------------------------------------------------------- disjoint from ir_validate
def test_a_gap_never_restates_a_validation_error(s3):
    """Removing the matcher is IR-001's job. The matcher-completeness rules must go
    quiet rather than piling on, or the error/question boundary blurs."""
    s3.certify.matchers = []
    assert "IR-001" in {i.rule for i in errors(validate(s3))}
    assert not (rules(s3) & {"CA-003", "CA-004", "CA-008"})


def test_rule_id_namespaces_do_not_collide(s3):
    assert not ({g.rule for g in advise(s3)} & {i.rule for i in validate(s3)})


def test_every_gap_states_a_consequence(s2, s3):
    """Advice fatigue is the stated risk; a question without a cost is ignorable."""
    probe = copy.deepcopy(s2)
    probe.certify.validations = []
    probe.certify.survivorship = []
    probe.model_ir.entities[0].subject_name = None
    for g in advise(probe) + advise(s3):
        assert g.consequence and g.consequence[-1] == "."


# ------------------------------------------------ CA-012 / CA-013 (house policy)
def test_a_computed_attribute_must_not_be_overridable(s3):
    """The operator's rule: overrides are for values a PERSON types. An enricher output
    that a steward can 'correct' is a value the next run recomputes and discards."""
    from agent.ir.advise import advise
    assert [g for g in advise(s3) if g.rule == "CA-012"] == []
    derived = next(r for r in s3.certify.survivorship if r.name == "DerivedRule")
    derived.override_strategy = "UNTIL_NEXT_USER_CHANGE"
    hit = [g for g in advise(s3) if g.rule == "CA-012"]
    assert hit and "NormalizedName" in hit[0].question


def test_an_in_place_normalizer_stays_overridable(s3):
    """Email <- LOWER(TRIM(Email)) still carries the publisher's value, so a steward
    edit is legitimate. Only a value computed FROM something else is pipeline-owned."""
    from agent.ir.advise import advise
    s3.certify.enrichers.append(type(s3.certify.enrichers[0])(
        entity="Party", name="TrimSourceKey", scope="PRE_CONSO",
        expressions=[{"attribute": "SourceKey", "expression": "TRIM(SourceKey)"}]))
    assert [g for g in advise(s3) if g.rule == "CA-012"] == []


def test_an_unnormalized_binning_key_is_caught_even_when_ca004_is_quiet(s3):
    """The gap CA-013 exists for. CA-004 asks whether ANY match input is normalized, so
    one normalized attribute hides every unnormalized one behind it. Scenarios 3 and 4
    both binned on raw address values while NormalizedName kept CA-004 silent."""
    from agent.ir.advise import advise
    assert [g for g in advise(s3) if g.rule == "CA-013"] == []
    s3.certify.enrichers = [e for e in s3.certify.enrichers
                            if e.name != "NormalizeAddress"]
    gaps = advise(s3)
    assert [g for g in gaps if g.rule == "CA-004"] == [], "CA-004 must stay quiet"
    hit = [g for g in gaps if g.rule == "CA-013"]
    assert hit and "StateCode" in hit[0].question and "Zip5" in hit[0].question


def test_ca013_applies_to_id_matched_entities_too(s2):
    """An ID-matched entity bins as well, and a raw binning key fails there for the same
    reason. CA-013 read a fuzzy-only variable at first and crashed on exactly this."""
    from agent.ir.advise import advise
    advise(s2)          # must not raise


def test_a_complex_attribute_binning_key_is_not_a_permanent_false_positive(s3):
    """Binning names the key `Address.Zip5` and the enricher writes `Address.Zip5`.
    Comparing a stripped name against an unstripped one fires forever."""
    from agent.ir.advise import advise
    assert [g for g in advise(s3) if g.rule == "CA-013"] == []
    assert any("." in b for x in s3.certify.matchers for r in x.rules for b in r.binning)


# ------------------------------------------------------- CA-014: earned auto-confirm
def test_auto_confirming_singletons_is_the_default_not_a_warning(s3):
    """The operator's correction: a steward clicking confirm on every unmatched record
    is a rubber stamp, not review. It manufactures an audit trail and spends attention
    that belongs on the 80-94 band. So auto-confirm is NOT questioned by itself."""
    from agent.ir import policy
    from agent.ir.advise import advise
    assert policy.AUTO_CONFIRM_SINGLETONS is True
    assert all(x.auto_confirm_singletons for x in s3.certify.matchers)
    assert [g for g in advise(s3) if g.rule == "CA-014"] == []


def test_auto_confirm_into_an_empty_process_is_questioned(s3):
    """What IS questioned is auto-confirming into a process with nothing to catch a bad
    record. The trust has to be earned."""
    from agent.ir.advise import advise
    s3.certify.validations = []
    hit = [g for g in advise(s3) if g.rule == "CA-014"]
    assert hit and "no PRE_CONSO validation" in hit[0].question


def test_auto_confirm_with_unnormalized_binning_is_questioned(s3):
    from agent.ir.advise import advise
    s3.certify.enrichers = [e for e in s3.certify.enrichers
                            if e.name != "NormalizeAddress"]
    hit = [g for g in advise(s3) if g.rule == "CA-014"]
    assert hit and "not normalized" in hit[0].question


def test_turning_auto_confirm_off_silences_the_rule(s3):
    """The rule is about earning trust, not about the flag. Switching singletons back to
    manual review removes the question it was asking."""
    from agent.ir.advise import advise
    s3.certify.validations = []
    for x in s3.certify.matchers:
        x.auto_confirm_singletons = False
    assert [g for g in advise(s3) if g.rule == "CA-014"] == []


def test_a_fuzzy_golden_id_is_not_counted_as_unenforced(s3):
    """A fuzzy entity's PK is generated by xDM, so `mandatory` with no scope is correct
    there. CA-010 already carries this exclusion; CA-014 missing it made the rule fire
    on both fuzzy scenarios that had done nothing wrong."""
    from agent.ir.advise import advise
    pk = next(a for e in s3.model_ir.entities for a in e.attributes if a.pk)
    assert pk.mandatory and pk.mandatory_scope == "NONE"
    assert [g for g in advise(s3) if g.rule == "CA-014"] == []


def test_a_zero_merge_threshold_is_caught(s3):
    """docs/Design/matching/automate-merge-and-confirmation.md: the threshold is the
    score "above which the match group is automatically merged". Zero means merge at
    any score, so nothing is ever suggested and the steward queue stays empty because
    nothing is sent to it.

    Worth a rule because it is the DEFAULT state of a new matcher — reached by not
    deciding, and indistinguishable from a deliberate merge-everything policy. Observed
    on a live model built in the UI: 6 of the 8 thresholds sat at 0."""
    from agent.ir.advise import advise
    assert [g for g in advise(s3) if g.rule == "CA-015"] == []
    m = s3.certify.matchers[0]
    m.thresholds = {**m.resolved_thresholds(), "mergeThresholdMergingUnconfirmed": 0}
    hit = [g for g in advise(s3) if g.rule == "CA-015"]
    assert hit and "merges at ANY score" in hit[0].question


def test_the_house_policy_thresholds_do_not_trip_ca015(s3):
    """95/80 derives eight non-zero thresholds, so a model following house policy must
    stay silent — otherwise the rule fires on every correct design."""
    from agent.ir import policy
    from agent.ir.advise import advise
    m = s3.certify.matchers[0]
    m.thresholds = {}
    m.policy = policy.HOUSE_THRESHOLDS
    assert all(v > 0 for v in m.resolved_thresholds().values())
    assert [g for g in advise(s3) if g.rule == "CA-015"] == []


def test_a_master_view_on_a_basic_entity_is_questioned(s3):
    """Master records only exist for ID- and fuzzy-matched entities, so MD and GDWE are
    meaningless on a Basic one. Documented twice. It fails as an EMPTY SCREEN rather
    than an error, which reads as 'no data' instead of 'wrong view type'."""
    from agent.ir.advise import advise
    from agent.ir.schema import (AppAction, Application, BOViewNode, BusinessView)
    e = s3.model_ir.entities[0]
    e.type = "basic"
    s3.app.business_views = [BusinessView(
        entity=e.name, name="V", root="R",
        nodes=[BOViewNode(name="R", entity=e.name)])]
    s3.app.applications = [Application(name="App", actions=[AppAction(
        kind="BrowseBusinessViewAction", name="Browse", view_entity=e.name,
        view="V", settings={"viewType": "MD"})])]
    hit = [g for g in advise(s3) if g.rule == "CA-016"]
    assert hit and "has no master records" in hit[0].question


def test_the_same_view_as_golden_data_is_fine(s3):
    from agent.ir.advise import advise
    from agent.ir.schema import (AppAction, Application, BOViewNode, BusinessView)
    e = s3.model_ir.entities[0]
    e.type = "basic"
    s3.app.business_views = [BusinessView(
        entity=e.name, name="V", root="R",
        nodes=[BOViewNode(name="R", entity=e.name)])]
    s3.app.applications = [Application(name="App", actions=[AppAction(
        kind="BrowseBusinessViewAction", name="Browse", view_entity=e.name,
        view="V", settings={"viewType": "GD"})])]
    assert [g for g in advise(s3) if g.rule == "CA-016"] == []


def test_a_fuzzy_entity_may_be_browsed_with_errors():
    """Verified live: FuzzyProve opened as GDWE, which is legal and must stay silent."""
    import pathlib
    from agent.compile.extract import extract
    from agent.compile.extract_app import extract_app
    from agent.compile.extract_certify import extract_certify
    from agent.ir.advise import advise
    from agent.ir.schema import IR as _IR
    p = ROOT / "samples" / "gs-customerb2c-2025.1.0.xml"
    if not p.exists():          # vendor demo export; not in the public export tree
        pytest.skip("samples/gs-customerb2c-2025.1.0.xml not present")
    full = _IR(model_ir=extract(p)[0], certify=extract_certify(p), app=extract_app(p))
    assert [g for g in advise(full) if g.rule == "CA-016"] == []


# --------------------------------------------- CA-018: the inbound value, overwritten
def test_an_enricher_that_overwrites_its_own_input_is_asked_about(s2):
    """LESSONS §47. The publisher's value and a derived value are different facts.
    LOWER(TRIM(Email)) cannot be un-lowered, so after the first load the question
    "what did the source actually send?" has no answer short of a reload."""
    s2.model_ir.acknowledged_gaps = []
    gaps = [g for g in advise(s2) if g.rule == "CA-018"]
    assert gaps, "writing an attribute from itself must raise CA-018"
    assert "unrecoverable" in gaps[0].consequence


def test_writing_a_DIFFERENT_attribute_is_not_a_gap(s2):
    """The rule must not fire on normal enrichment. NormalizedName <- UPPER(TRIM(Name))
    keeps both facts and is the shape CA-018 is steering toward — if this fired, the
    advice would be self-contradictory."""
    from agent.ir.schema import Enricher
    s2.model_ir.acknowledged_gaps = []
    s2.certify.enrichers = [Enricher(
        entity="Customer", name="Norm", kind="semql", scope="PRE_CONSO",
        expressions=[{"attribute": "RegionCode", "expression": "UPPER(TRIM(Email))"}])]
    assert not [g for g in advise(s2) if g.rule == "CA-018"]


def test_the_reference_scenario_no_longer_overwrites_anything(s4):
    """s4 was restructured for §47: normalized keys and address parts land in their own
    attributes. This is the regression guard on that, since the tempting simplification
    is always to write back over the input."""
    assert not [g for g in advise(s4) if g.rule == "CA-018"]
    names = {a.name for e in s4.model_ir.entities for a in e.attributes}
    assert {"ErpKey", "ErpKeyNorm"} <= names, "both the raw and the derived key survive"


def test_a_bin_is_never_coarser_than_the_equality_it_serves(s4):
    """LESSONS §46. Binning is the cost control: it decides which pairs are compared at
    all. P_NAME_STATE_ZIP binned on Address.StateCode alone — ~50 buckets — so every
    record in a US state was a candidate pair for every other. An over-matched group
    does not render slowly, it returns 504 on the duplicate manager's data call.

    The invariant: every binning key must appear in the rule's own condition, and a rule
    testing more than one equality must not bin on only the least selective one.
    """
    rule = next(r for x in s4.certify.matchers for r in x.rules
                if r.name == "P_NAME_STATE_ZIP")
    assert "NormalizedName" in rule.binning, \
        "the selective attribute must be in the bin, not just in the condition"
    for key in rule.binning:
        assert key in rule.condition, f"{key} bins on something the rule never tests"


# ------------------------------------------------ CA-019 / CA-020 (LESSONS §58)
def _s3():
    d = ROOT / "out/s3-three-sources/ir"
    if not (d / "app.yaml").exists():
        pytest.skip("s3 IR not present")
    return IR.load(d / "model.yaml", d / "certify.yaml", d / "app.yaml")


def test_ca019_a_workflow_that_discards_authored_data_is_asked_about():
    """Measured twice on 2026-08-08: the instance COMPLETED and no load was minted.
    The stepper authors, nothing submits, the steward's edit evaporates.

    s3 now carries the §58 FIX — a SUBMIT automation running INTEGRATE_DATA — so the
    shipped scenario has a submit path and does NOT fire. Stripping that step reinstates
    the discard, and then the question is asked."""
    ir = _s3()
    assert not [g for g in advise(ir) if g.rule == "CA-019"], \
        "shipped s3 has a SUBMIT automation, so nothing is discarded"

    # Remove the submit path: the review task's edit now evaporates at completion.
    ir_no_submit = copy.deepcopy(ir)
    w = ir_no_submit.model_ir.workflows[0]
    w.steps = [s for s in w.steps
               if not (s.type == "Automation" and s.automation_type == "SUBMIT_DATA")]
    hits = [g for g in advise(ir_no_submit) if g.rule == "CA-019"]
    assert len(hits) == 1 and "AuthorParty" in hits[0].question
    assert "discarded" in hits[0].question

    # A stepper that only VIEWS (no form step) does not fire: nothing is authored.
    ir2 = copy.deepcopy(ir_no_submit)
    ir2.app.steppers[0].steps = [
        s for s in ir2.app.steppers[0].steps if s.kind != "form"]
    assert not [g for g in advise(ir2) if g.rule == "CA-019"]


def test_ca020_an_unlabelled_user_transition_is_asked_about():
    """The steward's primary action rendered as a button called OUTGOING, because
    Transition.name defaults to 'outgoing' and nothing set a label. s3's IR now
    labels it, so the shipped scenario is clean and stripping the label fires."""
    ir = _s3()
    assert not [g for g in advise(ir) if g.rule == "CA-020"], \
        "the shipped s3 IR labels its user-facing transition"
    ir2 = copy.deepcopy(ir)
    for st in ir2.model_ir.workflows[0].steps:
        if st.type == "UserTask":
            st.transitions[0].label = None
    hits = [g for g in advise(ir2) if g.rule == "CA-020"]
    assert len(hits) == 1 and "'OUTGOING'" in hits[0].question
    # System-step edges render for nobody: the StartEvent's unlabelled transition
    # must never fire this rule.
    assert all("start" not in g.where.split("/")[-1] for g in hits)
